- hosts: fastapi
  become: true  # Run as sudo
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required dependencies
      apt:
        name:
          - python3
          - python3-pip
          - docker.io
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: "0755"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add Ubuntu user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Start FastAPI with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/fastapi_deploy/fastapi-app

